const BOARD_EVENT = {
  AA1: "Opening CA Open",
  AB1: "Cont.A Open",
  AB2: "Board Trading Close",
  AC2: "Closing CA Execution",
  AD1: "Order Reception Start",
  AD2: "CA Execution",
  AE1: "Market Halt Release",
  AE8: "Market Halt",
  AF1: "CA Open after CB",
  AF6: "CB Notice",
  AF7: "CB Notice Clear",
  AF8: "Suspension by CB",
  AQ3: "Interface Connection Cut-off",
  AT6: "PLE Notice",
  AW8: "Lunch Break",
  AW9: "Open after Lunch Break",
  AX1: "Board Start",
  BB1: "Cont.A Open for Non-PCA Instr.",
  BC1: "Closing CA Open",
  BE9: "Cont.A Open after Market Halt",
  BF9: "Cont.A Open after CB",
  CC1: "Closing PCA Open",
  CD1: "PCA Open",
  CD3: "PCA Execution",
  DB2: "Trading Close for LTD Instr.",
  DC2: "Closing CA Execution for LTD Instr.",
  EI1: "Trading Halt Release by Instr./Product",
  EI8: "Instr./Product Halt",
  EI9: "Cont.A Open after Instr./Product Halt",
  GT1: "GT Order Load",
}

module.exports = { BOARD_EVENT };