const MARKET_INDEX = {
  '001_STO': 'VNINDEX',
  '002_STX': 'HNXIndex',
  '003_STX': 'HNX Large Cap Index',
  '004_STX': 'HNX Mid/Small Cap Index',
  '100_STX': 'HNX30',
  '101_STO': 'VN30',
  '102_STO': 'VNMIDCAP',
  '103_STO': 'VNSMALLCAP',
  '104_STO': 'VN100',
  '105_STO': 'VNALLSHARE',
  '151_STO': 'VNXALLSHARE',
  '152_STO': 'VNX50',
  '200_STX': 'HNX Manufacturing Index',
  // '201_STO': undefined,
  '201_STX': 'HNX Construction Index',
  // '202_STO': undefined,
  '202_STX': 'HNX Financials Index',
  // '203_STO': undefined,
  // '204_STO': undefined,
  // '205_STX': undefined,
  '222_STX': 'HNX50',
  // '300_STX': undefined,
  '301_STO': 'VNAllShare Consumer Discretionary',
  '301_UPX': 'HNXUpcomIndex',
  '302_STO': 'VNAllShare Consumer Staples',
  '303_STO': 'VNAllShare Energy',
  '304_STO': 'VNAllShare Financials',
  '305_STO': 'VNAllShare Health Care',
  '306_STO': 'VNAllShare Industrials',
  '307_STO': 'VNAllShare Information Technology',
  '308_STO': 'VNAllShare Materials',
  '309_STO': 'VNAllShare Real Estate',
  '310_STO': 'VNAllShare Utilities',
  '310_UPX': 'UPCOM Large Index',
  '320_UPX': 'UPCOM Small Index',
  '330_UPX': 'UPCOM Medium Index',
  '401_STO': 'VN Sustainability Index',
  '401_STX': 'Consumer Staples Index',
  '402_STX': 'Financial Index GICS',
  '403_STX': 'HNX ENERGY INDEX',
  '501_STO': 'VN Diamond Index',
  '502_STO': 'VN Financial Select Sector Index',
  '503_STO': 'VN Leading Financial Index',
  // '601_STO': undefined,
  // '602_STO': undefined,
  // '603_STO': undefined,
};

module.exports = { MARKET_INDEX }