version: '3'
services:
  app:
    build: .
    ports:
      - '6789:6789'
    working_dir: /app
    environment:
      - REDIS_CONNECTION_STRING=redis://redis:6379
    depends_on:
      - mongo
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  redis-data:
  mongo-data:
